version: '3.8'
services:
  discovery-service:
    build: ./discovery-service
    image: generalstore/discovery-service
    depends_on:
      - mongo
    ports:
      - "8761:8761"
    networks:
      - generalstore-network

  gateway:
    build: ./gateway
    image: generalstore/gateway
    depends_on:
      - mongo
      - discovery-service
    ports:
      - "8080:8080"
    networks:
      - generalstore-network

  inventory-service:
    build: ./inventory-service
    image: generalstore/inventory-service
    depends_on:
      - mongo
      - discovery-service
    ports:
      - "8082:8082"
    networks:
      - generalstore-network

  product-service:
    build: ./product-service
    image: generalstore/product-service
    depends_on:
      - mongo
      - discovery-service
    ports:
      - "8081:8081"
    networks:
      - generalstore-network

  user-service:
    build: ./user-service
    image: generalstore/user-service
    depends_on:
      - mysql-user
      - discovery-service
    ports:
      - "8083:8083"
    networks:
      - generalstore-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user:3306/user_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
    networks:
      - generalstore-network

  mongo:
    image: mongo:6
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - generalstore-network

volumes:
  mongo_data:
  mysql_user_data:

networks:
  generalstore-network:
    driver: bridge
